# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'searchArticleUI.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1000, 750)
        Dialog.setMinimumSize(QtCore.QSize(1000, 750))
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.comboBox = QtWidgets.QComboBox(Dialog)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.horizontalLayout.addWidget(self.comboBox)
        self.lineEdit = QtWidgets.QLineEdit(Dialog)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout.addWidget(self.lineEdit)
        self.search = QtWidgets.QPushButton(Dialog)
        self.search.setObjectName("search")
        self.horizontalLayout.addWidget(self.search)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.statusLabel = QtWidgets.QLabel(Dialog)
        self.statusLabel.setObjectName("statusLabel")
        self.verticalLayout_3.addWidget(self.statusLabel)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.titleList = QtWidgets.QListWidget(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.titleList.sizePolicy().hasHeightForWidth())
        self.titleList.setSizePolicy(sizePolicy)
        self.titleList.setMinimumSize(QtCore.QSize(550, 0))
        self.titleList.setObjectName("titleList")
        self.verticalLayout.addWidget(self.titleList)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.showMore = QtWidgets.QPushButton(Dialog)
        self.showMore.setObjectName("showMore")
        self.horizontalLayout_3.addWidget(self.showMore)
        self.sizeCombox = QtWidgets.QComboBox(Dialog)
        self.sizeCombox.setMinimumSize(QtCore.QSize(60, 0))
        self.sizeCombox.setObjectName("sizeCombox")
        self.sizeCombox.addItem("")
        self.sizeCombox.addItem("")
        self.sizeCombox.addItem("")
        self.sizeCombox.addItem("")
        self.horizontalLayout_3.addWidget(self.sizeCombox)
        self.tiaoJieguo = QtWidgets.QLabel(Dialog)
        self.tiaoJieguo.setMinimumSize(QtCore.QSize(50, 0))
        self.tiaoJieguo.setAlignment(QtCore.Qt.AlignCenter)
        self.tiaoJieguo.setObjectName("tiaoJieguo")
        self.horizontalLayout_3.addWidget(self.tiaoJieguo)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.clearList = QtWidgets.QPushButton(Dialog)
        self.clearList.setObjectName("clearList")
        self.horizontalLayout_3.addWidget(self.clearList)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.infBrowser = QtWidgets.QTextBrowser(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.infBrowser.sizePolicy().hasHeightForWidth())
        self.infBrowser.setSizePolicy(sizePolicy)
        self.infBrowser.setMinimumSize(QtCore.QSize(350, 0))
        self.infBrowser.setObjectName("infBrowser")
        self.verticalLayout_2.addWidget(self.infBrowser)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.clearBrowser = QtWidgets.QPushButton(Dialog)
        self.clearBrowser.setObjectName("clearBrowser")
        self.horizontalLayout_2.addWidget(self.clearBrowser)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.verticalLayout_2.setStretch(0, 1)
        self.horizontalLayout_4.addLayout(self.verticalLayout_2)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "论文信息索引"))
        self.label.setText(_translate("Dialog", "检索类型："))
        self.comboBox.setItemText(0, _translate("Dialog", "标题"))
        self.comboBox.setItemText(1, _translate("Dialog", "作者"))
        self.comboBox.setItemText(2, _translate("Dialog", "关键词"))
        self.search.setText(_translate("Dialog", "检索"))
        self.statusLabel.setText(_translate("Dialog", "欢迎使用！"))
        self.showMore.setText(_translate("Dialog", "再显示"))
        self.sizeCombox.setItemText(0, _translate("Dialog", "100"))
        self.sizeCombox.setItemText(1, _translate("Dialog", "500"))
        self.sizeCombox.setItemText(2, _translate("Dialog", "1000"))
        self.sizeCombox.setItemText(3, _translate("Dialog", "5000"))
        self.tiaoJieguo.setText(_translate("Dialog", "条结果"))
        self.clearList.setText(_translate("Dialog", "清除结果"))
        self.infBrowser.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.clearBrowser.setText(_translate("Dialog", "清除页面"))

